# Dingo Den
[[server]]
id = 178042794386915328
gamba.points_name = "cheddar"
[server.roles]
self_assign = [ 745821300987002912, 862135223072194571 ]
no_pings = [552399444105232384, 492485748071727129]
[server.cooldown]
default_seconds = 15
exempt = [876683421601136650]
[server.automod]
text_prefix = "<@&492485748071727129> Problematic message detected. Please select an appropriate action below."
log_channel = 552398918865125376
[server.commands]
whiskey.enabled = true
collect.enabled = false
[server.logging]
log_channel = 552398918865125376
message_deleted = true

# Lycaon
[[server]]
id = 351122293105229835
automod.log_channel = 895922436250406912
gamba.points_name = "lycoins"
[server.cooldown]
default_seconds = 5
exempt = [ 895922436250406912 ]
[server.roles]
self_assign = [ 908285057498751007, 875679251704193037, 878827554222538854, 890676584867049482, 911082035978858556, 975088367408644177, 975088699845013504 ]
[server.commands]
ref.enabled = true

# Discorg
[[server]]
id = 768208778780475447
gamba.points_name = "nuggies"
[server.roles]
no_pings = [768232863043682314, 768233366889300028]
[server.cooldown]
default_seconds = 15
exempt = [903465905630089236]
[server.automod]
log_channel = 790632143037399070
text_prefix = "<@&768232863043682314> Problematic message detected. Please select an appropriate action below."
[server.commands]
corgi.enabled = true
roles.enabled = false
waffle.enabled = true

# GlexSiba
[[server]]
id = 840467720695971840
gamba.points_name = "shiba stars"
[server.roles]
no_pings = [863866217445326858]
self_assign = [968735501194494002]
[server.cooldown]
default_seconds = 15
exempt = [859278418511003698]
[server.commands]
snipe.enabled = false

# Test bot
[[server]]
id = 970811039635628072
[server.roles]
self_assign = [971942005871640666, 971942064843542548]
no_pings = []
[server.cooldown]
default_seconds = 15
exempt = [840021184589856778]
[server.automod]
log_channel = 941073180003561514
text_prefix = "<@749862270129143880> This is a test."
[server.commands]
echo.enabled = true
collect.enabled = true
ref.enabled = true

# Test bot 2
[[server]]
id = 971905014379458590
