# Dingo Den
[[server]]
id = 178042794386915328
gamba.points_name = "cheddar"
no_pings = [ 552399444105232384, 492485748071727129 ]
[server.cooldown]
default_seconds = 15
exempt = [876683421601136650]
[server.automod]
text_prefix = "<@&492485748071727129>"
log_channel = 552398918865125376
scam_filter = true
age_filter = true
max_channels_per_min = 5
raid_min_users = 15
raid_window_hours = 1
[server.commands]
whiskey.enabled = true
collect.enabled = false
[server.logging]
log_channel = 552398918865125376
message_deleted = true
user_banned = true
[[server.self_assign_roles]]
id = 745821300987002912
description = "Get notified for movie nights!"
emoji = "ğŸ¬"
[[server.self_assign_roles]]
id = 908285057498751007
description = "Get notified about gaming events on the server!"
emoji = "ğŸ®"

# Lycaon
[[server]]
id = 351122293105229835
automod.log_channel = 895922436250406912
gamba.points_name = "lycoins"
profile.channel = 1028131083105095680
[server.cooldown]
default_seconds = 5
exempt = [ 895922436250406912 ]
[server.commands]
profile.enabled = true
[[server.self_assign_roles]]
id = 908285057498751007
description = "Get notified about VRChat events"
emoji = "ğŸ¥½"
[[server.self_assign_roles]]
id = 911082035978858556
description = "Let everyone else on the server ping you."
emoji = "ğŸ””"
[[server.self_assign_roles]]
id = 975088367408644177
description = "Get notified for tabletop game events"
emoji = "â™Ÿï¸"
[[server.self_assign_roles]]
id = 1026704638155694110
description = "Get notified for D&D RPG game events"
emoji = "ğŸ²"
[[server.self_assign_roles]]
id = 1026700452626169856
description = "Get notified for Pokemon D&D RPG game events"
emoji = "ğŸŒ•"
[[server.self_assign_roles]]
id = 975088699845013504
description = "Get notified for BOTC games"
emoji = "ğŸ•°ï¸"
[[server.self_assign_roles]]
id = 985980186019389461
description = "Get notified when you're available for betrayal."
emoji = "ğŸ "
[[server.self_assign_roles]]
id = 984907652163309598
description = "Get notified for Furality related information."
emoji = "ğŸŠ"
[[server.self_assign_roles]]
id = 988646156131262513
description = "Use this role to show you can provide help with Unity."
emoji = "ğŸ§Š"
[[server.self_assign_roles]]
id = 993291228416323644
description = "Get pinged for convention-related messages."
emoji = "ğŸ«‚"
[[server.self_assign_roles]]
id = 1032382194829754419
description = "Did you know that it has a free trial?"
emoji = "âš”ï¸"
[[server.self_assign_roles]]
id = 875679251704193037
emoji = "â¤ï¸"
[[server.self_assign_roles]]
id = 878827554222538854
emoji = "â¤ï¸"
[[server.self_assign_roles]]
id = 890676584867049482
emoji = "â¤ï¸"

# Discorg
[[server]]
id = 768208778780475447
gamba.points_name = "nuggies"
no_pings = [768232863043682314, 768233366889300028]
[server.cooldown]
default_seconds = 15
exempt = [903465905630089236]
[server.automod]
log_channel = 790632143037399070
text_prefix = "<@&768232863043682314>"
scam_filter = true
age_filter = true
max_channels_per_min = 5
raid_min_users = 12
raid_window_hours = 1
[server.commands]
corgi.enabled = true
waffle.enabled = true
[[server.twitter.rules]]
filter = "from:TheCorgiCam -is:reply"
channel = 834538416427237376
message = "<@&768650292644282408> Corgi just posted a new tweet!"
[[server.self_assign_roles]]
id = 768650292644282408
description = "Get notified when Corgi tweets and goes live in the Discorg!"
emoji = "ğŸ›ï¸"
[[server.self_assign_roles]]
id = 990196640000376874
description = "Get notified when Julune posts about commissions!"
emoji = "ğŸ¨"
[[server.self_assign_roles]]
id = 990196515144368168
description = "Get notified about movie nights!"
emoji = "ğŸ¿"

# GlexSiba
[[server]]
id = 840467720695971840
no_pings = [863866217445326858]
[servere.automod]
log_channel = 863865546684497960
text_prefix = "<@&863866859061379133> "
scam_filter = true
max_channels_per_min = 5
[server.cooldown]
default_seconds = 15
exempt = [859278418511003698]
[server.commands]
snipe.enabled = false
gamba.enabled = false
[[server.self_assign_roles]]
id = 968735501194494002
description = "Use this role to get pinged for movie nights!"
emoji = "ğŸ¿"

# Test bot
[[server]]
id = 970811039635628072
profile.channel = 995749304453050428
[server.cooldown]
default_seconds = 15
exempt = [840021184589856778]
[server.automod]
log_channel = 970811039635628075
[server.logging]
log_channel = 970811039635628075
user_banned = true
message_deleted = true
[server.commands]
echo.enabled = true
collect.enabled = true
profile.enabled = true
[[server.self_assign_roles]]
id = 971942005871640666
description = "First Role"
emoji = "ğŸ‘Œ"
[[server.self_assign_roles]]
id = 971942064843542548
description = "Second Role"
emoji = "ğŸ"
[[server.twitter.rules]]
filter = "from:SnazzyTest -is:reply"
channel = 970811039635628075
message = "This is a test tweet from my test account."

# Test bot 2
[[server]]
id = 971905014379458590
[server.automod]
raid_min_users = 1
raid_window_hours = 0.1
log_channel = 971905015079911497