[[server]]
id = 814653859838427136

[server.roles]
mods = [869729094722543627]
self_assign = [873029553918967889, 908451036308590593]
no_pings = []
mute = 908451036308590593

[server.cooldown]
default_seconds = 60
exempt = [840021184589856778]

[server.automod]
log_channel = 870516696593596506
text_prefix = "<@749862270129143880> This is a test."

[server.commands]
echo.enabled = true
collect.enabled = true
roles.enabled = true
collect.permissions = [869729094722543627]